version: '3.1'

services:
  postgres:
    image: postgres:latest-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_LOGIN: postgres
      POSTGRES_DBNAME: psyc
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


  golang:
    build: ./
    ports:
      - 80:80