server:
  addr: localhost:8080
  debug: true
  timeout: 10

postgres:
  host: localhost
  port: 5432
  user: root
  password: root
  database: golang

redis:
  addr: localhost:6379
  database: 0
  password: 
  user: user

