server:
  addr: localhost:8000
  debug: true
  timeout: 10

postgres:
  host: localhost
  port: 5432
  user: root
  password: root
  database: golang

redis:
  addr: localhost:6379
  database: 0
  password: 
  user: user

mail:
  mail: #TODO
  password: #TODO
  host: smtp.mail.ru
  port: 587

bot:
  token: 6746766492:AAFZo1PkufL5lgttpBJ7lns4WnTbayIutAE
  whurl: https://ghoul-causal-snipe.ngrok-free.app
  port: 80